# примеры API-запросов

@baseUrl = https://localhost:8000/api
###

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8905b87eae0960a7e88d6a23d71caf8eb43ae31a

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token 8905b87eae0960a7e88d6a23d71caf8eb43ae31a
#Authorization: Token a0546bcfa7c26e64824051cc8cf1632fd7dc4baf

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-12-12
Content-Type: application/json
