# примеры API-запросов

@baseUrl = https://localhost:8000/api
###

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
#Authorization: Token 28482ae8ac89ca747e5328a1aa19063c68851d69
Authorization: Token 9aa60f5735492182d42d98b68c31c5cf415bb57c

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 28482ae8ac89ca747e5328a1aa19063c68851d69
#Authorization: Token 28482ae8ac89ca747e5328a1aa19063c68851d69

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator_id=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-12-12
Content-Type: application/json
